# -*- coding: utf-8 -*-
"""2ndProgram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFbJLwtyjf3Wqe9svA3y0u5tlL01HD8Q
"""

import numpy as np
a1=np.array([10,15,20,25,30])
print(a1)
mat1=np.array([[10,15,20],[25,30,35],[40,45,50]])
print(mat1)

#array , 2d array print

np.arange(1,10)
#renge data print

np.linspace(1,15,8)
#8 random numbers print between renge

np.random.rand(5)

np.random.randint(1,20,10)
#random number print

import numpy as np
li=[3,4,5,8,9,11]
arr1=(np.array(li))
print(arr1)
#list to array

t1=(3,4,7,8,9)
arr2=np.array(t1)
print(arr2)
#tupple to Array

d1={'a':10,'b':20,'c':30}
arr3=np.array(list(d1.keys()))
arr3=np.array(list(d1.values()))
arr3=np.array(list(d1.items()))
print(arr3)
#Distionary

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
m=np.mean(data)
print(m)
#mean calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
me=np.median(data)
print(me)
#median calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,40,45,70,60])
mo=stats.mode(data)
print(mo)
#mode calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
r1=np.max(data)-np.min(data)
print(r1)
#range calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
r2=np.ptp(data)
print(r2)
#range calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
ve=np.var(data)
print(ve)
#Varience calculate using nampy

import numpy as np
from scipy import stats
data=np.array([10,20,30,40,50,60])
sd=np.std(data)
print(sd)
#standard deviation calculate using nampy

import matplotlib.pyplot as plt
list1=[4,8,9,12,16,8]
plt.plot(list1)
plt.show()

x=[0,5,10,15]
y=[2,7,8,11]
plt.plot(x,y)
plt.title("Student data")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.show()