# -*- coding: utf-8 -*-
"""Class5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3IPSQLYD3cyyzy2YgYnN5MZGvO-SgPm
"""

import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)

s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

data={'Jan': 1200, 'Feb': 1500, 'Mar': 1800}
sales = pd.Series(data)
print(sales)
print(sales['Feb'])
print(sales[1])

sales*2

print(s+100)

data={
    'Name':['Tom','Jack','Steve','Ricky'],
    'Age':[28,34,29,42],
    'Salary':[50000,15000,58880,45000]
}
df=pd.DataFrame(data)
print(df)

data=pd.DataFrame([
    ['Alice',25,50000]
    ['Bob',35,55000]

])

print(df['Age'])
print()   #column
print(df[['Age','Salary']])
print()
print(df.loc[0])
print() #Row data access by Level
print(df.iloc[0]) #row data access by index

print(df['Salary']*1.1) #salary hike
print(df['Age'].mean()) #age mean
print(df['Age'].max()) #age max
print(df['Age'].min()) #age min
print(df['Age'].sum()) #age sum
print(df['Age'].count()) #age count
print(df['Age'].median()) #age median
print(df['Age'].std()) #age std
print(df['Age'].var()) #age var

df['Bouns']=df['Salary']*0.1  #add column (DAX)
df['Total Salary']=df['Salary']+df['Bouns']
print(df)

df.drop('Total Salary',axis=1,inplace=True) #inplace- delete from  main  table
print(df)

print(df)

df.shape

df.info()

df.describe()

import numpy as np
import pandas as pd
arr=np.array([1,2,3,4,5])
s=pd.Series(arr,name='Age',index=['A','B','C','D','E'])
print(s)

import numpy as np
import pandas as pd
#arr1=np.array([[2,24000],[6,30000],[5,15200]])
#print(arr1)
s=pd.DataFrame(arr1,columns=['ID','Salary'],index=['A','B','C'])
print(s)