# -*- coding: utf-8 -*-
"""Class3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiXMZJhJckPhDrHwbHNQyd40vk-t4xtU
"""

import numpy as np
np.full((3,3),5)

arr=np.arange(1,8)
print(arr)
arr2=np.arange(1,8,2)
print(arr2)
#renge

arr3=np.linspace(1,8,5)
print(arr3)
#step

np.eye(4)
#identity matrix

arr4=np.array([1,2,3])
print(type(arr4))

arr=np.array([1,2,3],dtype=np.float64)
print(arr.dtype)
#data type casting

arr=np.array([1,2.7,3],dtype=np.int64)
print(arr.dtype)
print(arr)
#data type casting, data loss(2.6->2)

import numpy as np
arr=np.array([
     [10,20,30],
     [40,50,60]
 ])
 print("Dimensuons:", arr.ndim) #2-number of dimensions
 print("Shape:", arr.shape) #(2,3)-structure of the array
 print("Size:", arr.size) # 6-Total Number of Elements
 print("Item Size:", arr.itemsize,"bytes") #8-Memory per elements
 print("Data Type:", arr.dtype) #int64 -datatype

import numpy as np
data=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
    [100,110,120]
])
print(data[0])
print(data[:2])
print(data[2,0])
print(data[0:2,0:1])
data>50
print(data[(data>50)])

np.where(data>50,"High","Low")

#Slicing And Indexing
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80])
print(arr[0])#first element
print(arr[3])#fourth element
print(arr[-1])#last element
print(arr[-2])#second last element

a=np.array([10,20,30])
print(np.power(a,2)) #square
print(np.sqrt(a)) #square root
print(a>20) #boolean
print(a[a>20]) #filter

arr=np.array([
    [10,25,30],[40,55,65],[75,85,95]
    ])
print(np.mean(arr,axis=0))
print(np.median(arr,axis=0))
print(np.std(arr,axis=0))
print(np.var(arr,axis=0))
print(np.min(arr,axis=0))
print(np.max(arr,axis=0))

data=np.array([10,20,30,40,50,60,70,80,90,100,120,1000])
print(np.percentile(data,25))#percentage function
print(np.percentile(data,50))
print(np.percentile(data,75))
print(np.percentile(data,100))

Q1=np.percentile(data,25)
Q3=np.percentile(data,75)
IQR=Q3-Q1
print(IQR)
lower_bound=Q1-(1.5*IQR)
upper_bound=Q3+(1.5*IQR)
print(lower_bound)
print(upper_bound)
outliers=data[(data<lower_bound) | (data>upper_bound)]
print(outliers)



