# -*- coding: utf-8 -*-
"""class7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkwiznbgrpjbX9baHOcOpULk1uIdQLv6
"""

import matplotlib.pyplot as plt
import numpy as np
x=[1,2,3,4,5]
y=[10,20,30,40,50]
plt.bar(x,y)
plt.show()

category=['A','B','C','D','E']
value=[10,20,30,40,50]
plt.pie(value,labels=category,autopct='%1.1f%%',explode=[0,0.2,0.1,0.1,0.2])
plt.show()



