# -*- coding: utf-8 -*-
"""Class6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RK19YamTEuUEh-k2bpi45i6YXqSFxLD
"""

import pandas as pd
df = pd.read_excel("/content/Sample_data.xls")
print(df)

df.columns   #show columns header

df.rename({'Postal Code' : 'Pin Code'},axis=1,inplace=True)   #rename column
print(df)

df.columns

df.rename({'Row ID' : 'Index'},axis=1,inplace=True)   #rename column
print(df)

df.columns

print(df)

df.drop(['Index'],axis=1,inplace=True)   #drop column
print(df)

df.columns

df.isnull().sum()*100/len(df)   #check null values

from enum import unique
df['Category'].unique() #unique values find

df['Profit'].fillna(0,inplace=True) #fill null values
print(df)

df.columns

df[df['State'].isna()]   #find row where state is not given(blank)

df[df['Customer ID'].isna()]['State'],['Country']

df.dropna(subset=['State'],inplace=True)    # if you want to remove the row where there is a blank in state
print(df)

df.dtypes    #check datatype

df=df.astype({'Discount': 'int64'})   #change data type
df.dtypes

df.columns.str.strip().str.lower().str.replace(" ","_") # strip - trim extra space remove . lower - case conversion,replace - replace value with given value

