# -*- coding: utf-8 -*-
"""FirstProgram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137xdSj7JYUX7wHHNzNf776CeV2SfrCw_

#It is My First Python Program
"""

print("Rul Amin, It's Your First Program")

list=[10,20,30,40,50]
print(max(list))
print(min(list))
print(list)
print((list[1]))
for i in list:
  print (i)
list.append(20)
print(list)
list.remove(20)
print(list)
list[1]=22
print(list)
print(type(list))

list=[10,20,30,40,50]
for i in range(len(list)):
  print(list[i])

for i in range(10):
  print(i,end=" ")

print("Even Numbers = ")
for i in range(2,50,2):
  print(i,end=" ")

print("Odd Numbers = ")
for i in range(1,50,2):
  print(i,end=" ")

t1=(1,4,6)
print(t1)
print(type(t1))

l1=[]
t1=()
print(type(l1))
print(type(t1))

l1=[1]
t1=(1)
print(type(l1))
print(type(t1))

l1=[1]
t1=(1,)
print(type(l1))
print(type(t1))

l1=[1,2]
t1=(1,2)
print(type(l1))
print(type(t1))

def sum(): #defination
  a=2
  b=3
  c=a+b
  print(c)
sum()   #calling

def sum():
  a=2
  b=3
  c=a+b
  return c
x=sum()
print(x)
print("The value is ", sum())

def sum(a,b):
  c=a+b
  print(c)
sum(4,5)

def sum(a,b):
  c=a+b
  return c
x=sum(5,5)
print(x)